version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      # Check for updates at 00:00 UTC
      time: "00:00"
    groups:
      maven-plugins:
        patterns:
          - "org.apache.maven.plugins:*"
          - "org.sonatype.central:*"
